// Merges translator output into src/core/dict.js. Run after tests/extract.mjs.
import fs from 'node:fs';
const L = ['ms', 'zh', 'ar'].map((l) => JSON.parse(fs.readFileSync(`tests/tr-${l}.json`, 'utf8')));
let prev = {}; try { prev = (await import('../src/core/dict.js?' + Date.now())).DICT; } catch {}
const keys = JSON.parse(fs.readFileSync('tests/strings.json', 'utf8'));
const out = {};
for (const k of [...new Set([...Object.keys(prev), ...keys, ...Object.keys(L[0])])].sort()) {
  const row = [0, 1, 2].map((i) => L[i][k] ?? prev[k]?.[i]);
  if (row.every(Boolean)) out[k] = row;
}
fs.writeFileSync('src/core/dict.js', '// Generated by tests/build-dict.mjs: English source → [Malay, Chinese, Arabic].\nexport const DICT = ' + JSON.stringify(out, null, 0).replace(/\],"/g, '],\n"') + ';\n');
console.log('entries', Object.keys(out).length);
