// Control centre (staff preview): monitor money, orders, warehouse, customers, factories and support.
import { html, raw } from '../core/html.js';
import { t, tl, ago } from '../core/i18n.js';
import { page, on, S, money, render } from '../app.js';
import { trialBalance, isBalanced, ACC } from '../core/ledger.js';
import { byId } from '../domain/catalog.js';
import { nextStep, canRefund } from '../domain/escrow.js';
import { validCode } from '../domain/rules.js';
import * as svc from '../domain/services.js';
import { ic } from '../ui/icons.js';
import { confirm, prompt, toast } from '../ui/ui.js';
import { stateText } from './orders.js';
import { stateLabel } from './home.js';

const TABS = [['overview', 'Overview'], ['orders', 'Orders'], ['warehouse', 'Warehouse'], ['customers', 'Customers'], ['factories', 'Factories'], ['money', 'Money'], ['support', 'Support'], ['audit', 'Audit log']];
let q = '';

function body(tab) {
  const s = S();
  switch (tab) {
    case 'orders': return html`<div class="card tbl-wrap"><table class="tbl"><thead><tr><th>${t('Order')}</th><th>${t('Customer')}</th><th>${t('Product')}</th><th>${t('Held')}</th><th>${t('Step')}</th><th>${t('Action')}</th></tr></thead><tbody>${s.orders.map((o) => { const n = nextStep(o.state); return html`<tr><td data-l="${t('Order')}" class="num">${o.id}</td><td data-l="${t('Customer')}"><span class="code">${s.profile.code}</span></td><td data-l="${t('Product')}">${tl(byId(o.pid).n)} × ${o.qty}</td><td data-l="${t('Held')}" class="num">${money(o.goods + o.insp)}</td><td data-l="${t('Step')}">${stateText(o.state)}</td><td data-l="${t('Action')}"><span class="row">${n ? html`<button class="btn ${n === 'released' ? 'primary' : 'ghost'} sm" data-a="cadv" data-id="${o.id}" data-to="${n}">${n === 'released' ? t('Release escrow') : t('Mark: {s}', { s: stateText(n) })}</button>` : ''}${canRefund(o) ? html`<button class="btn ghost sm" data-a="crefund" data-id="${o.id}">${t('Refund')}</button>` : ''}</span></td></tr>`; })}</tbody></table></div>`;
    case 'warehouse': return html`<section class="card"><div class="pad" style="padding-bottom:0"><b>${t('Receiving')}</b></div><div class="list">${s.parcels.filter((p) => p.state === 'coming').map((p) => html`<div class="li"><span class="mid"><b>${p.id} · ${p.name}</b><small>${p.courier} · ${t('{n} ctn', { n: p.cartons })} · <span class="code">${s.profile.code}</span></small></span><button class="btn primary sm" data-a="crecv" data-id="${p.id}">${t('Receive')}</button></div>`)}${s.parcels.some((p) => p.state === 'coming') ? '' : html`<p class="muted pad">${t('Nothing waiting.')}</p>`}</div></section>
      <section class="card sec"><div class="pad" style="padding-bottom:0"><b>${t('Shipments')}</b></div><div class="list">${s.shipments.map((x) => html`<div class="li"><span class="mid"><b>${x.id} · ${x.name}</b><small>${x.tracking} · ${t(stateLabel(x.state))}</small></span>${x.state !== 'delivered' ? html`<button class="btn ghost sm" data-a="cship" data-id="${x.id}">${t('Next step')}</button>` : html`<span class="pill good">${t('Delivered')}</span>`}</div>`)}</div></section>`;
    case 'customers': {
      const list = s.customers.filter((c) => !q || c.code.includes(q.toUpperCase()) || c.name.toLowerCase().includes(q.toLowerCase()));
      return html`<input class="inp" data-cq value="${q}" placeholder="${t('Find by customer code or name')}" aria-label="${t('Find customer')}" style="margin-bottom:8px"><div class="card tbl-wrap"><table class="tbl"><thead><tr><th>${t('Code')}</th><th>${t('Name')}</th><th>${t('Trust score')}</th><th>${t('Orders')}</th><th>${t('Status')}</th><th>${t('Action')}</th></tr></thead><tbody>${list.map((c) => html`<tr><td data-l="${t('Code')}"><span class="code">${c.code}</span> ${validCode(c.code) ? '' : html`<span class="pill warn">${t('bad code')}</span>`}</td><td data-l="${t('Name')}">${c.name}</td><td data-l="${t('Trust score')}">${c.score}</td><td data-l="${t('Orders')}">${c.orders}</td><td data-l="${t('Status')}"><span class="pill ${c.state === 'active' ? 'good' : c.state === 'frozen' ? 'red' : 'warn'}">${t({ active: 'Active', review: 'Review', frozen: 'Frozen' }[c.state])}</span></td><td data-l="${t('Action')}">${c.state === 'frozen' ? html`<button class="btn ghost sm" data-a="cstate" data-code="${c.code}" data-st="active">${t('Unfreeze')}</button>` : html`<button class="btn ghost sm" data-a="cstate" data-code="${c.code}" data-st="frozen">${t('Freeze')}</button>`}</td></tr>`)}</tbody></table></div>`;
    }
    case 'factories': return html`<section class="card"><div class="pad" style="padding-bottom:0"><b>${t('Applications')}</b></div><div class="list">${s.applications.map((a) => html`<div class="li"><span class="mid"><b>${a.n}</b><small>${a.id} · ${a.city} · ${a.type} · ${ago(a.at)}</small></span>${a.state === 'pending' ? html`<span class="row"><button class="btn primary sm" data-a="capp" data-id="${a.id}" data-ok="1">${t('Approve')}</button><button class="btn ghost sm" data-a="capp" data-id="${a.id}" data-ok="0">${t('Reject')}</button></span>` : html`<span class="pill ${a.state === 'approved' ? 'good' : 'red'}">${t(a.state === 'approved' ? 'Approved' : 'Rejected')}</span>`}</div>`)}</div></section><p class="note sec">${ic('shield', 14)} ${t('Factories below 75 for 14 days are paused automatically. Brand copies are rejected.')}</p>`;
    case 'money': { const tb = trialBalance(s.ledger); return html`<div class="health ${isBalanced(s.ledger) ? 'ok' : 'bad'}">${ic(isBalanced(s.ledger) ? 'check' : 'alert', 16)} ${isBalanced(s.ledger) ? t('Ledger balanced: every transaction sums to zero ({n} transactions)', { n: s.ledger.length }) : t('Ledger out of balance: check now')}</div>
      ${(s.supplierHolds || []).length ? html`<section class="card sec"><div class="pad" style="padding-bottom:0"><b>${t('Supplier payments held in escrow')}</b></div><div class="list">${s.supplierHolds.map((h) => html`<div class="li"><span class="mid"><b>${h.sup} · ${money(h.sen)}</b><small class="num">${h.ref} · ${h.via}</small></span>${h.state === 'held' ? html`<span class="row"><button class="btn primary sm" data-a="csup" data-ref="${h.ref}" data-ok="1">${t('Release')}</button><button class="btn ghost sm" data-a="csup" data-ref="${h.ref}" data-ok="0">${t('Refund')}</button></span>` : html`<span class="pill ${h.state === 'paid' ? 'good' : 'warn'}">${t(h.state === 'paid' ? 'Paid' : 'Refunded')}</span>`}</div>`)}</div></section>` : ''}
      <div class="card tbl-wrap sec"><table class="tbl"><thead><tr><th>${t('Account')}</th><th>${t('Balance')}</th></tr></thead><tbody>${Object.entries(tb).sort().map(([a, v]) => html`<tr><td data-l="${t('Account')}" class="num">${a}</td><td data-l="${t('Balance')}" class="num">${money(v)}</td></tr>`)}</tbody></table></div>
      <div class="card list sec">${[...s.ledger].reverse().slice(0, 30).map((x) => html`<div class="li"><span class="mid"><b>${x.memo}</b><small class="num">${x.id} · ${x.lines.map((l) => `${l.a} ${l.v > 0 ? '+' : ''}${(l.v / 100).toFixed(2)}`).join(' | ')}</small></span><span class="end small muted">${ago(x.at)}</span></div>`)}</div>`; }
    case 'support': return html`<div class="card list">${s.tickets.map((x) => html`<div class="li" style="align-items:flex-start"><span class="mid"><b>${x.id} · ${x.subject}</b><small><span class="code">${x.who}</span> · ${ago(x.at)}</small>${x.msgs.map((m) => html`<small style="white-space:normal">${m.from}: ${m.text}</small>`)}</span><span class="stack" style="gap:4px;align-items:flex-end"><span class="pill ${x.state === 'open' ? 'warn' : 'good'}">${t(x.state === 'open' ? 'Waiting' : 'Answered')}</span><button class="btn ghost sm" data-a="creply" data-id="${x.id}">${t('Reply')}</button></span></div>`)}</div>`;
    case 'audit': return html`<div class="card list">${s.audit.slice(0, 80).map((a) => html`<div class="li"><span class="mid"><b>${a.what}</b><small>${a.who} · <span class="num">${a.ref}</span></small></span><span class="end small muted">${ago(a.at)}</span></div>`)}</div>`;
    default: {
      const tb = trialBalance(s.ledger), open = s.orders.filter((o) => !['delivered', 'refunded'].includes(o.state));
      const act = [...s.orders.filter((o) => o.state === 'inspected').map((o) => [t('Release payment for {id}', { id: o.id }), 'orders']), ...s.parcels.filter((p) => p.state === 'coming').map((p) => [t('Receive and measure {id}', { id: p.id }), 'warehouse']), ...s.applications.filter((a) => a.state === 'pending').map((a) => [t('Review factory application {n}', { n: a.n }), 'factories']), ...s.tickets.filter((x) => x.state === 'open').map((x) => [t('Answer ticket {id}', { id: x.id }), 'support']), ...(s.supplierHolds || []).filter((h) => h.state === 'held').map((h) => [t('Decide supplier payment {id}', { id: h.ref }), 'money'])];
      return html`<div class="health ${isBalanced(s.ledger) ? 'ok' : 'bad'}">${ic(isBalanced(s.ledger) ? 'check' : 'alert', 16)} ${isBalanced(s.ledger) ? t('All systems normal · ledger balanced') : t('Ledger out of balance: check now')}</div>
      <div class="kpis sec"><div class="card kpi"><span>${t('Held in escrow')}</span><b class="num">${money((tb[ACC.ESCROW] || 0) + (tb[ACC.DEPOSIT] || 0))}</b></div><div class="card kpi"><span>${t('Open orders')}</span><b>${open.length}</b></div><div class="card kpi"><span>${t('Parcels in warehouse')}</span><b>${s.parcels.filter((p) => p.state === 'stored').length}</b></div><div class="card kpi"><span>${t('Open tickets')}</span><b>${s.tickets.filter((x) => x.state === 'open').length}</b></div></div>
      <section class="card sec"><div class="pad" style="padding-bottom:0"><b>${t('Needs action')}</b></div><div class="list">${act.length ? act.map(([txt, tb2]) => html`<a class="li" href="#control/${tb2}"><span class="ic out">${ic('bolt', 15)}</span><span class="mid"><b>${txt}</b></span>${ic('arrow', 16)}</a>`) : html`<p class="muted pad">${t('Nothing waiting.')}</p>`}</div></section>`;
    }
  }
}

page('control', {
  title: () => t('Control centre'),
  view(tab = 'overview') {
    if (!TABS.some((x) => x[0] === tab)) tab = 'overview';
    return html`<div class="page-h"><h1>${t('Control centre')}</h1><p>${t('Staff preview with sample data. Every action asks for confirmation and is written to the audit log.')}</p></div>
    <nav class="ctl-nav" aria-label="${t('Sections')}">${TABS.map(([k, n]) => html`<a class="chip ${k === tab ? 'on' : ''}" href="#control/${k}">${t(n)}</a>`)}</nav>${body(tab)}`;
  },
  mount(root) { const i = root.querySelector('[data-cq]'); if (i) { i.oninput = () => { q = i.value.slice(0, 30); const pos = i.selectionStart; render(); const j = document.querySelector('[data-cq]'); if (j) { j.focus(); j.setSelectionRange(pos, pos); } }; } },
});

const run = (fn, ok) => { try { fn(); toast(ok, 'good'); } catch (e) { toast(t(e.message), 'bad'); } };
on('cadv', async (el) => { const to = el.dataset.to; if (await confirm({ title: to === 'released' ? t('Release escrow to the factory?') : t('Move order to “{s}”?', { s: stateText(to) }), text: el.dataset.id, ok: t('Confirm') })) run(() => svc.advanceOrder(el.dataset.id, to, 'Control'), t('Updated')); });
on('crefund', async (el) => { const v = await prompt({ title: t('Refund {id}', { id: el.dataset.id }), text: t('The full amount goes back to the customer. This cannot be undone.'), ok: t('Refund'), fields: [{ name: 'why', label: t('Reason'), value: t('Failed inspection'), required: true, max: 80 }] }); if (v) run(() => svc.advanceOrder(el.dataset.id, 'refunded', 'Control', v.why), t('Refunded')); });
on('crecv', async (el) => { const v = await prompt({ title: t('Receive {id}', { id: el.dataset.id }), ok: t('Save measurements'), fields: [{ name: 'kg', label: t('Weight (kg)'), value: '12.5', inputmode: 'decimal', required: true }, { name: 'dim', label: t('Total size L × W × H (cm)'), value: '60 × 40 × 35', required: true }, { name: 'ph', label: t('Photos taken'), value: '6', inputmode: 'numeric' }], }); if (!v) return; const d = (v.dim.match(/\d+(\.\d+)?/g) || []).map(Number); if (d.length !== 3 || !(parseFloat(v.kg) > 0)) { toast(t('Enter weight and size'), 'bad'); return; } run(() => svc.receiveParcel(el.dataset.id, { grams: Math.round(parseFloat(v.kg) * 1000), cm3: Math.round(d[0] * d[1] * d[2]), photos: Math.min(20, parseInt(v.ph, 10) || 4) }), t('Parcel received')); });
on('cship', async (el) => { if (await confirm({ title: t('Move shipment to the next step?'), text: el.dataset.id })) run(() => svc.advanceShipment(el.dataset.id), t('Updated')); });
on('cstate', async (el) => { if (await confirm({ title: el.dataset.st === 'frozen' ? t('Freeze this customer?') : t('Unfreeze this customer?'), text: el.dataset.code, danger: el.dataset.st === 'frozen' })) run(() => svc.setCustomerState(el.dataset.code, el.dataset.st), t('Updated')); });
on('capp', async (el) => { const ok = el.dataset.ok === '1'; if (await confirm({ title: ok ? t('Approve this factory?') : t('Reject this factory?'), text: el.dataset.id, danger: !ok })) run(() => svc.decideApplication(el.dataset.id, ok), t('Updated')); });
on('csup', async (el) => { const ok = el.dataset.ok === '1'; if (await confirm({ title: ok ? t('Pay the supplier from escrow?') : t('Refund this supplier payment to the customer?'), text: el.dataset.ref, danger: !ok })) run(() => svc.settleSupplierHold(el.dataset.ref, ok), t('Updated')); });
on('creply', async (el) => { const v = await prompt({ title: t('Reply to {id}', { id: el.dataset.id }), ok: t('Send'), fields: [{ name: 'm', label: t('Message'), type: 'textarea', required: true, max: 1000 }] }); if (v) run(() => svc.replyTicket(el.dataset.id, v.m), t('Sent')); });
